# NumPy

## **Notes**

* NumPy thư viện làm việc với mảng hiệu quả và ma trận mạng đa chiều lớn
* Thư viện NumPy có tốc độ và hiệu quả trong các phép toán số học
* Một số trường hợp sử dụng đặc biệt của NumPy trong phân tích dữ liệu:
    * Các phép toán trên mảng
    * Đại số tuyến tính
    * Các hàm thống kê
    * Sinh số ngẫu nhiên
* **Tạo Mảng**:
    * Vd: **`import numpy as np; np.array([1, 2, 3])`**
* **Các Phép Toán Cơ Bản**: Các phép toán như `+`, `-`, `/`, `*` được thực hiện trên từng phần tử của mảng.
* **Cắt Mảng**:
    * Vd: **`array[1:3]`**: Lấy các phần tử từ chỉ số 1 đến chỉ số 3 (không bao gồm 3).
* **Chỉ Mục với điều kiện**:
    * Vd: **`array[array > 0]`**: Lấy các phần tử trong mảng thỏa mãn điều kiện.


### Tạo mảng

In [35]:
import numpy as np

In [36]:
#Mảng toàn số 0
zeros = np.zeros((2, 3))
print(zeros)

# Mảng toàn số 1
ones = np.ones((3, 3))
print(ones)

# Mảng với các giá trị ngẫu nhiên
random = np.random.rand(3, 4)
print(random)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.89869984 0.08302251 0.10555425 0.99387361]
 [0.42494204 0.15924937 0.44202966 0.51749652]
 [0.61363197 0.99126953 0.14678471 0.3534055 ]]


### Các phép toán cơ bản:

In [37]:
years_of_experience = np.array([1, 2, 3, 4, 5])
years_of_experience

array([1, 2, 3, 4, 5])

#### Cộng

In [38]:
years_of_experience_plus_one = years_of_experience + 1
years_of_experience_plus_one

array([2, 3, 4, 5, 6])

#### Trừ

In [39]:
years_of_experience_minus_one = years_of_experience - 1
years_of_experience_minus_one

array([0, 1, 2, 3, 4])

#### Chia

In [40]:
years_of_experience_half = years_of_experience / 2
years_of_experience_half

array([0.5, 1. , 1.5, 2. , 2.5])

#### Nhân

In [41]:
years_of_experience_double = years_of_experience * 2
years_of_experience_double

array([ 2,  4,  6,  8, 10])

### Cắt

`array[start: end]`

lấy phần tử từ chỉ số star đến end ( không lấy end)

In [42]:
second_and_third_jobs_experience = years_of_experience[1: 3]
second_and_third_jobs_experience

array([2, 3])

### Lấy phần tử với chỉ mục có điều kiện

`array[aray > 2]`

lấy phần tử lớn hơn 2

In [43]:
jobs_with_more_than_one_year_exp = years_of_experience[years_of_experience > 2]
jobs_with_more_than_one_year_exp

array([3, 4, 5])

### Notes

* các hàm tính toán:
    * `sum`: Tính tổng
    * `prod`: Tính tích
    * `cumsum`: Tính tổng cộng dồn
    * `cumprod`: Tính tích cộng dồn
    * `sqrt`: Tính cân bậc hai
    * `exp` : Hàm mũ
    * `log` : Logarit
    * `sin` : Hàm sin
    * `cos` : Hàm cos

    ....

### Ví dụ

In [44]:
import random 
import numpy as np

# Dùng .randint(a, b) để tạo 1 số ngẫu nhiên trong khoảng (a, b)
salary = [random.randint(100000, 150000) for num in range(10)]

In [45]:
salary

[139535,
 130345,
 106347,
 143594,
 116414,
 143819,
 108074,
 145329,
 121530,
 139519]

In [46]:
# Chuyển thành mảng
salary_array = np.array(salary)
salary_array

array([139535, 130345, 106347, 143594, 116414, 143819, 108074, 145329,
       121530, 139519])

### Sum 

In [47]:
total_sum_salaries = np.sum(salary_array)
print(total_sum_salaries)

1294506


### Prod

In [48]:
product_salaries = np.prod(salary_array)
print(product_salaries)
# Do kết quẩ quá lớn nên kết quả sẻ nhận được có đáu -

-5366962012458907984


### Cumsum

- Phần tử đầu tiên của `cumsum` là 110003 (chỉ là phần tử đầu tiên)
- Phần tử thứ hai là 110003 + 133394 = 243397
- Phần tử thứ ba là 243397 + 148741 = 392138
- Và tiếp tục...

In [49]:
cumulative_sum_salaries = np.cumsum(salary_array)
cumulative_sum_salaries

array([ 139535,  269880,  376227,  519821,  636235,  780054,  888128,
       1033457, 1154987, 1294506])

### Cumprod 

- Phần tử đầu tiên của `cumprod` là 110003 (chỉ là phần tử đầu tiên)
- Phần tử thứ hai là 110003 * 133394
- Phần tử thứ ba là (110003 * 133394) * 148741
- Và tiếp tục...

In [50]:
cumulative_prod_salaries = np.cumprod(salary_array)
cumulative_prod_salaries

array([              139535,          18187689575,     1934206223232525,
        1039247313207920610,  9189084399630394812,  3290341744054593556,
        2508138057117469512, -2467193676013222712, -4669271811904222896,
       -5366962012458907984])

### Notes

* `mean` : Trung bình
* `median` : Trung vị
* `var`: Phương sai
* `std`: Độ lệch chuẩn
* `min`: GTNN
* `max`: GTLN

### Mean

In [51]:
average_salary = np.mean(salary_array)
average_salary

np.float64(129450.6)

### Median 

In [52]:
median_salary = np.median(salary_array)
median_salary

np.float64(134932.0)

### Var 

* `ddof=0`: Hàm sẽ tính phương sai tổng thể
* `ddof=1`: Hàm tính phương sai mẫu

In [53]:
salary_variance = np.var(salary_array, ddof=1)
salary_variance

np.float64(231766914.04444447)

### Std

* `ddof=0`: Hàm tính độ lệch chuẩn tổng thể
* `ddof=1`: Hàm tính độ lệch chuẩn mẫu

In [54]:
salary_std_dev = np.std(salary_array, ddof=1)
salary_std_dev

np.float64(15223.892867609273)

### Min

In [55]:
min_salary = np.min(salary_array)
min_salary

np.int64(106347)

### Max

In [56]:
max_salary = np.max(salary_array)
max_salary

np.int64(145329)

### Notes

* Cú pháp: `np.nan`
* Giá trị `np.nan`: thể hiện dữ liệu còn thiếu hoặc là chưa xác định.
* Hữu ích vì:
    * Xử lý dữ liệu thiếu.
    * Giúp tính toán vì nó sẽ không trả về lỗi mà thay vào đó trả về `np.nan`.
    * Giúp lọc hoặc điền dữ liệu thiếu bằng các phương pháp khác

### Ví dụ

In [57]:
salary_with_nan = np.array([123124, np.nan, 145000, 128000, 110000, 149999, np.nan, 135000, 115000, 140000], dtype=float)
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

#### Thay thế

In [58]:
# Thay thế các giá trị dưới 130000 thành nan
salary_with_nan[salary_with_nan < 130000] = np.nan
salary_with_nan

array([    nan,     nan, 145000.,     nan,     nan, 149999.,     nan,
       135000.,     nan, 140000.])

### Notes

* Cú pháp: `np.where(condition)`.
* `np.where` kiểm tra các phần tử của một mảng theo một điều kiện và gán một giá trị cho True và một giá trị khác cho False
* Nó thường được sử dụng để thay thế các phần tử trong mảng theo điều kiện.

### Ví dụ

In [59]:
# Thay thế các phần tử nhỏ hơn 120000 thành 120000 
salary_array = np.where(salary_array < 120000, 120000, salary_array)
salary_array

array([139535, 130345, 120000, 143594, 120000, 143819, 120000, 145329,
       121530, 139519])

## Random Sampling

* Cú pháp tạo ra các số ngẫu nhiên hoặc các mẫu ngẫu nhiên
* Cú pháp: `np.random.normal(mean, std_dev, size)`: Rút ra mẫu ngẫu nhiên từ phân phối chuẩn
    * `mean`:Trung vị của phân phối chuẩn
    * `std_dev`: Độ lệch chuẩn của phân phối chuẩn
    * `size`: Xác định số lượng mẫu ngẫu nhiên cần rút

### [xem nhiều hơn tại đây](https://numpy.org/doc/2.1/reference/random/legacy.html)

#### Ví dụ


In [60]:
noise = np.random.normal(0, 5000, salary_array.size)
print(noise)

print(salary_array)

salary_array_with_noise = salary_array + noise
salary_array_with_noise

[ -3373.06939983   -969.51159267   4666.04111188   -370.83267974
 -11787.4490022    4775.93353769  -5966.62105735   2904.69135375
   6386.63982278   1492.68217521]
[139535 130345 120000 143594 120000 143819 120000 145329 121530 139519]


array([136161.93060017, 129375.48840733, 124666.04111188, 143223.16732026,
       108212.5509978 , 148594.93353769, 114033.37894265, 148233.69135375,
       127916.63982278, 141011.68217521])